config/routes.rb
RedditOnRails::Application.routes.draw do

  devise_for :users

  resources :pages
  root :to => "pages#index"

  resources :links
  resources :comments
  resources :votes

  get 'search' => 'search#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :message, :user_id, :link_id

  belongs_to :link
  belongs_to :user

end

app/models/link.rb
class Link < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :url, :title, :user_id
  belongs_to :user
  has_many :comments
  has_many :votes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :username, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :links
  has_many :comments
  has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
  attr_accessible :up, :link_id

  validates :user_id, :uniqueness => { :scope => :link_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :authenticate_user!
  
  def create
  	@comment = current_user.comments.create(params[:comment])
    redirect_to :back		
	end  
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def show
  	@link    = Link.find(params[:id])
    @comment = Comment.new
  end

  def new
  	@link = Link.new
  end

  def create
    @link = Link.new(params[:link])                 

    respond_to do |format|
      if @link.save
       format.html { redirect_to @link, notice: 'Link was successfully updated.' }
       #format.html { render :action => "create", notice: 'Link was successfully created.' }
       format.json { render :json => @link }
      else
         format.html { render :action => "new" }
       format.json { render :json => @link.errors, :status => :unprocessable_entity }
      end
    end  
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		# @links = Link.includes(:user).all

		@links = Link.paginate(:page => params[:page] ||= 25, :order => params[:order], :per_page => params[:per_page] ||= 3)
	end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	def index
		@links = Link.search(:title => params[:q]).page(params[:page]).per_page(3)
	end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  before_filter :authenticate_user!
  
  def create
  	@vote = current_user.votes.where(:link_id => params[:vote][:link_id]).first
	@vote ||= current_user.votes.create(params[:vote])
	@vote.update_attributes(:up => params[:vote][:up])
	redirect_to :back
	end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
  <title>RedditOnRails</title>

    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>


    <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap.css" rel="stylesheet">
    <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap-responsive.css" rel="stylesheet">

    <%= stylesheet_link_tag    "application", :media => "all" %>

    <script src="http://heroku.github.com/template-app-bootstrap/jquery-1.7.1.min.js"></script>
    <script src="http://heroku.github.com/template-app-bootstrap/jquery.replacetext.min.js"></script>

    <!--
      IMPORTANT:
      This is Heroku specific styling. Remove to customize.
    -->
    <link href="http://heroku.github.com/template-app-bootstrap/heroku.css" rel="stylesheet">
    <!-- /// -->

    <!--
      IMPORTANT:
      To do the replacement  example for the real name application
    -->
    <script src="http://heroku.github.com/template-app-bootstrap/heroku.js"></script>
    <!-- /// -->


  </head>

  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a href="/" class="brand">Reddit on Rails</a>
          <div class='nav-collapse'>
            <ul class='nav'>
              <%# user is logged in, show log out link %>
              <% if current_user.present? %>
                <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
              <%# user is not logged in, show signup and login links %>
              <% else %>
                <li><%= link_to 'Sign In', new_user_session_path %></li> |
                <li><%= link_to 'Register Now!', new_user_registration_path %></li>
              <% end %>
            </ul>
          </div>
          <!--
            IMPORTANT:
            This is Heroku specific markup. Remove to customize.
          -->
          <a href="/" class="brand" id="heroku">by <strong>heroku</strong></a>
          <!-- /// -->
        </div>
      </div>
    </div>

    <div class="container" id="getting-started">
      <div class="row">
        <div class="span6 offset2">
        <div class="page-header"></div>
  <% [:notice, :error, :alert].each do |level| %>
  <% unless flash[level].blank? %>
    <div data-alert="alert" class="alert alert-<%= level %> fade in">
      <a class="close" data-dismiss="alert" href="#">&times;</a>
      <%= content_tag :p, flash[level] %>
    </div>
  <% end %>
<% end %>

<%= content_for :sidebar do %>
  <%= link_to "Add a link", new_link_path %><br />
<% end %>

<%= content_for :sidebar do %>
  <%= link_to "Awesome Blog", 'http://schneems.com' %>
<% end %>

<%= form_tag(search_path, :method => "get", :style => "margin: 5px 0 0 0") do %>
  <%= text_field_tag(:q, nil, :placeholder => "search") %>
  <%= submit_tag("Search") %>
<% end %>

          <%= yield %>
          <%= yield :sidebar %>


          
        </div>
      </div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/links/create.html.erb
<h1>I'm the create view</h1>

<h2>Link Created Successfully<h2>

<%= @link.title %> added to the website, url: <%= @link.url %>

<div>

<%= link_to "Links homepage", pages_path %>
</div>

app/views/links/new.html.erb
<h1>I'm the new view</h1>
 <%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_user.present?
      x = current_user.id
    else 
      x = "nil"
    end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
    <%= f.hidden_field :user_id, :value => x %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/show.html.erb
<h1>Show view for link: <%= @link.url %> by: <%= @link.user.email %> </h1>

<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message, :placeholder => "Add a comment" %>
    <%= f.hidden_field :link_id, :value => @link.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<h2>Comments:<h2>
<div>
  <% @link.comments.each do |comment| %>
    <p><%= comment.message %> by: <%= comment.user.email %> at: <%= comment.created_at %></p>
  <% end %>
</div>

app/views/pages/index.html.erb
<br></br>
<%= will_paginate @links %>

<h2>I am a homepage</h2>
<%= link_to "Add a link", new_link_path %>

<p></p>

<h1>Links</h1>

<ul>
  <% @links.each do |link| %>
    <li><%= link_to link.title , link.url %> by: <%= 
    		if link.user.present?
    		link.user.email
    		else
    		"no user"  
    		end
    	%></br>

    <% if current_user && current_user.votes.where(:link_id => link.id, :up => true).present? %>
    *
    <% else %>
    <%= link_to "+", votes_path(:vote => {:link_id => link.id, :up => true}), :method => :post %>
    <% end %> 
    / 
    <% if current_user && current_user.votes.where(:link_id => link.id, :up => false).present? %>
    *
    <% else %>
    <%= link_to "-", votes_path(:vote => {:link_id => link.id, :up => false}), :method => :post %>
    <% end %>

    </br>

    Votes: <%= link.votes.where(:up => true).count - link.votes.where(:up => false).count %>
    
    <p></p>
    <%= link_to "comments", link %>	
    <p></p>
    </li>
  <% end %>
</ul>

app/views/search/index.html.erb
<%= will_paginate @links %>

Here are all the links that matched "<%= params[:q] %>"
<ul>
  <% @links.each do |link| %>
    <li>
      Votes: <%= link.votes.where(:up => true).count - link.votes.where(:up => false).count %>

      <% if current_user && current_user.votes.where(:link_id => link.id, :up => true).present? %>
      *
      <% else %>
        <%= link_to "+", votes_path(:vote => {:link_id => link.id, :up => true}), :method => :post %>
      <% end %>


      <% if current_user && current_user.votes.where(:link_id => link.id, :up => false).present? %>
        *
      <% else %>
          <%= link_to "-", votes_path(:vote => {:link_id => link.id, :up => false}), :method => :post %>
      <% end %>

      <%= link_to link.title, link.url %>
      <%= link_to "comments", link %>
    </li>
  <% end %>
</ul>